### ISSUE TITLE
[label: help wanted] About dataset

### ISSUE THREAD

**Issue by LinkaSage** [EmoryHuang/maran#1]
Thank you for your excellent work! 
However, I have a question, that is, your dataset seems to be a soft route (maybe not), and there is no real dataset. Can you share the dataset you use? 
Thank you very much

**Comment by LinkaSage** [comment]
Sorry, I didn't read the Readme section carefully. I'm very sorry. Thank you again for your excellent work.

**Comment by EmoryHuang** [comment]
Thank you for your interest. This study uses the same dataset as Graph-Flashback, which you can find a [link](https://drive.google.com/file/d/1zup1aP2JvkrpdYNXQnqlvzsQvZcgA7QN/view?usp=share_link) in the readme, or in the [Graph-Flashback](https://github.com/kevin-xuan/Graph-Flashback). Also the original dataset should be sourced from [Foursquare](https://sites.google.com/site/yangdingqi/home) and [Gowalla](http://snap.stanford.edu/data/loc-gowalla.html).

**Comment by LinkaSage** [comment]
Yes, I see. Thank you very much for your reply! You will be an excellent scholar and open source contributor!
